# Generated by Django 5.0.8 on 2024-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_colaborador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Colaborador')),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('aparencia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_colaboradores/', verbose_name='Foto do Colaborador')),
            ],
        ),
    ]
