# Generated by Django 5.0.8 on 2024-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Colaborador'),
        ),
    ]
