# Generated by Django 5.0.8 on 2024-08-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_colaboradores_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave API'),
        ),
    ]
