# Generated by Django 5.0.8 on 2024-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_colaboradores_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('contratacao', 'Em Contratação'), ('demitido', 'Demitido')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
