# Generated by Django 5.0.8 on 2024-08-15 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprendizado', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendizados_colaborador', to='colaboradores.colaboradores', verbose_name='Aprendizados do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Atuais_Demandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuais_demandas', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizada')], default='P', max_length=1, verbose_name='Status da Tarefa')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atuais_demandas_colaborador', to='colaboradores.colaboradores', verbose_name='Atuais Demandas do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conhecimento_geral', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conhecimentos_colaborador', to='colaboradores.colaboradores', verbose_name='Conhecimentos do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta_De_Conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_conhecimento', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_conhecimentos_colaborador', to='colaboradores.colaboradores', verbose_name='Consulta de Conhecimentos do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.IntegerField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos_colaborador', to='colaboradores.colaboradores', verbose_name='Custos do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_colaborador', to='colaboradores.colaboradores', verbose_name='Experiências do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa_de_trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utils', models.TextField(blank=True, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('forms', models.TextField(blank=True, null=True)),
                ('admin', models.TextField(blank=True, null=True)),
                ('views', models.TextField(blank=True, null=True)),
                ('models', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_de_trabalho_colaborador', to='colaboradores.colaboradores', verbose_name='Mesas de Trabalho do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Personalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personalidade', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalidades_colaborador', to='colaboradores.colaboradores', verbose_name='Personalidades do Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes_colaborador', to='colaboradores.colaboradores', verbose_name='Sugestões do Colaborador')),
            ],
        ),
    ]
