# Generated by Django 5.0.8 on 2024-08-15 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa_de_trabalho',
            old_name='admin',
            new_name='mesa',
        ),
        migrations.RemoveField(
            model_name='mesa_de_trabalho',
            name='forms',
        ),
        migrations.RemoveField(
            model_name='mesa_de_trabalho',
            name='models',
        ),
        migrations.RemoveField(
            model_name='mesa_de_trabalho',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='mesa_de_trabalho',
            name='utils',
        ),
        migrations.RemoveField(
            model_name='mesa_de_trabalho',
            name='views',
        ),
    ]
