# Generated by Django 5.0.8 on 2024-08-25 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0002_rename_admin_mesa_de_trabalho_mesa_and_more'),
        ('colaboradores', '0003_colaboradores_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa_de_trabalho',
            name='colaborador_responsavel_tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mesas_de_trabalho_colaborador_responsavel_tarefa', to='colaboradores.colaboradores', verbose_name='Mesas de Trabalho do Colaborador Responsável Tarefa'),
        ),
        migrations.AddField(
            model_name='mesa_de_trabalho',
            name='id_tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tarefa_relacionada', to='cerebro.atuais_demandas', verbose_name='Id da Tarefa Relacionada'),
        ),
        migrations.AlterField(
            model_name='mesa_de_trabalho',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_de_trabalho_colaborador_criador', to='colaboradores.colaboradores', verbose_name='Mesas de Trabalho do Colaborador Criador'),
        ),
    ]
