# Generated by Django 5.0.8 on 2024-09-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0004_remove_mesa_de_trabalho_colaborador_responsavel_tarefa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atuais_demandas',
            name='incluir_github_files',
            field=models.BooleanField(default=False),
        ),
    ]
