# Generated by Django 5.0.8 on 2024-09-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0005_atuais_demandas_incluir_github_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='atuais_demandas',
            name='resumo_tarefa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
