# Generated by Django 5.0.8 on 2024-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0006_atuais_demandas_resumo_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa_de_trabalho',
            name='versao_revisada',
            field=models.IntegerField(default=1),
        ),
    ]
