# Generated by Django 5.0.8 on 2024-09-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerebro', '0007_mesa_de_trabalho_versao_revisada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuais_demandas',
            name='resumo_tarefa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
