# Generated by Django 5.0.8 on 2024-09-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_file', models.TextField(blank=True, null=True)),
                ('views_file', models.TextField(blank=True, null=True)),
                ('urls_file', models.TextField(blank=True, null=True)),
                ('forms_file', models.TextField(blank=True, null=True)),
                ('utils_file', models.TextField(blank=True, null=True)),
                ('admin_file', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
