# Generated by Django 5.0.8 on 2024-09-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
