# Generated by Django 5.0.8 on 2024-10-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customusuario_imagem_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='clickup_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API ClickUp'),
        ),
        migrations.AddField(
            model_name='customusuario',
            name='clickup_list_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='List ID ClickUp'),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave API OpenAI'),
        ),
    ]
