# Generated by Django 5.0.8 on 2024-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customusuario_clickup_api_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='udemy_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token API Udemy'),
        ),
        migrations.AddField(
            model_name='customusuario',
            name='udemy_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Udemy Client ID'),
        ),
        migrations.AddField(
            model_name='customusuario',
            name='udemy_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Udemy Client Secret'),
        ),
    ]
