# Generated by Django 5.0.8 on 2024-10-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_customusuario_udemy_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='udemy_access_token',
        ),
    ]
