# Generated by Django 5.0.8 on 2024-10-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_customusuario_udemy_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusuario',
            name='udemy_client_id',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='udemy_client_secret',
        ),
    ]
