# Generated by Django 5.0.8 on 2024-10-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaclickup',
            name='data_inicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefaclickup',
            name='data_vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
