# Generated by Django 5.0.8 on 2024-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tarefaclickup_data_inicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaclickup',
            name='status',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
