# Generated by Django 5.0.8 on 2024-10-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tarefaclickup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaclickup',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
