# Generated by Django 5.0.8 on 2024-10-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tarefaclickup_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
