# Generated by Django 5.0.8 on 2024-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_compromisso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoUdemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('progresso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
