# Generated by Django 5.0.8 on 2024-10-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_cursoudemy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CursoUdemy',
        ),
    ]
