# Generated by Django 5.0.8 on 2024-10-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_compromisso_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='recorrente',
            field=models.CharField(choices=[('N', 'Não Recorrente'), ('D', 'Diariamente'), ('S', 'Semanalmente'), ('M', 'Mensalmente')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='repeticoes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
