# Generated by Django 5.0.8 on 2024-10-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_compromisso_recorrente_compromisso_repeticoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='dias_da_semana',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='recorrente',
            field=models.CharField(choices=[('N', 'Não Recorrente'), ('D', 'Diariamente'), ('S', 'Semanalmente'), ('M', 'Mensalmente'), ('A', 'Anualmente')], default='N', max_length=1),
        ),
    ]
