# Generated by Django 5.0.8 on 2024-10-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_compromisso_data_termino_compromisso_dias_da_semana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='dias_da_semana',
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='recorrente',
        ),
        migrations.RemoveField(
            model_name='compromisso',
            name='repeticoes',
        ),
    ]
